coverage:
  status:
    project:
      default:
        # Fail if coverage drops below current level
        target: auto
        # Fail if coverage decreases by more than 2%
        threshold: 2%
    patch:
      default:
        # New code should have at least 30% coverage (realistic given platform-specific code)
        target: 30%

comment:
  # Show coverage diff in PR comments
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
