coverage:
  status:
    project:
      default:
        # Minimum absolute coverage floor - never go below this
        target: 60%
        # Fail if coverage decreases by more than 1% (strict regression prevention)
        threshold: 1%
    patch:
      default:
        # New code must have at least 80% coverage
        # Strict to prevent untested code from entering codebase
        target: 80%
  # Require CI to pass coverage checks
  require_ci_to_pass: true

comment:
  # Show coverage diff in PR comments
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

# Strict settings to fight regressions
codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
